### ISSUE TITLE
birthdate date calculation is inaccurate

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1125]
in models.py in `def age_group_conf(self):`

```
attendee_age = (day - self.birthdate).days / 365.2425
```

we're doing a hokey calculation here and should not be using 365.2425 which probably glosses over some nasty leap-year edge cases.

in subsequent discussions, we should be using something like `dateutils.relativedelta` instead to do this computation.

whoever fixes this should do it Test Driven Development-style:
1) write a unit test showing the current code failing
2) fix that broken test by fixing the code

**Comment by kitsuta** [comment]
@EliAndrewC this is your change from the merge branch.

**Comment by thaeli** [comment]
Wait, WHAT? This will fail in some edge cases of people near the age cutoff
due to leap years. Can we please use a proper date library function to do
this conversion?

**Comment by binary1230** [comment]
Oh yea that's a good point too. Sounds like a great bug for @Lusarien to work on and write some unit tests for

**Comment by Lusarien** [comment]
Alright I will give it a look on Monday!

**Comment by kitsuta** [comment]
Hm, whoops. I have no idea why I didn't do that in the first place.

At any rate, it looks like you want dateutils.relativedelta for this.

**Comment by EliAndrewC** [comment]
A proper date library would be good, though I wouldn't want to hold up fixing this bug for that.  Although I think this WAS fixed in a different PR anyway, so maybe we could re-title this issue to be about making the larger leap-year fix rather than fixing the typo, which I don't *think* is still in master at this point anyway.

**Comment by binary1230** [comment]
quick note: the self.birthdate portion of this has been fixed.

the part that is still bad is the hardcoded divide by 365.2425

whoever is redoing this code should write a failing unit test where we don't handle the edge case, fix the bug, and get the test passing again.

**Comment by bds002** [comment]
I'm not sure if this is still open as an issue, I'm adding it to the MAGLites list.

**Comment by binary1230** [comment]
yea it is still an open issue.  the name and subject of this issue changed over time, I am going to cull discussion related to the original bug, which is fixed, to only include stuff about the new bug, which is not fixed.

**Comment by binary1230** [comment]
turns out I didn't need to cull anything. BUG READY FOR FIXIN
